// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmzdU01_3tR-EpdavsFz7L0czxlDriSR4',
    appId: '1:517811102592:web:539ddb97b08cabbb9c5765',
    messagingSenderId: '517811102592',
    projectId: 'chatapp-af5d3',
    authDomain: 'chatapp-af5d3.firebaseapp.com',
    storageBucket: 'chatapp-af5d3.appspot.com',
    measurementId: 'G-YDPT5SBKTQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmAZN6FQxuQ5UPKUPeZdHkFznV3aBjJxs',
    appId: '1:517811102592:android:a18514e0f8564b0c9c5765',
    messagingSenderId: '517811102592',
    projectId: 'chatapp-af5d3',
    storageBucket: 'chatapp-af5d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-jEKe_rZZm0pgr_gkZ_p6WSOeUjWhXOQ',
    appId: '1:517811102592:ios:871969cea269f4d99c5765',
    messagingSenderId: '517811102592',
    projectId: 'chatapp-af5d3',
    storageBucket: 'chatapp-af5d3.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-jEKe_rZZm0pgr_gkZ_p6WSOeUjWhXOQ',
    appId: '1:517811102592:ios:42f1e0a3b1e3a0cc9c5765',
    messagingSenderId: '517811102592',
    projectId: 'chatapp-af5d3',
    storageBucket: 'chatapp-af5d3.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
